const farms={
 libertad:{name:'Finca La Libertad',owner:'Soledad Sánchez',emoji:'🐄',place:'Montería',production:'Ganadería',secondary:'Piscicultura',weather:'☀️ 29° · Montería',first:'Soledad',users:[['SS','Soledad Sánchez','Propietaria','Acceso total'],['CS','Carlos Suárez','Socio / esposo','Operación y finanzas'],['JM','José Martínez','Encargado','Producción e inventario'],['DR','Dra. Laura Ruiz','Profesional técnico','Sanidad animal'],['AM','Ana Mejía','Consulta','Solo lectura']]},
 villayolsa:{name:'VillaYolsa',owner:'Yoleyda Sánchez',emoji:'🌾',place:'Cereté',production:'Cultivo de arroz',secondary:'Lotes y ciclos',weather:'🌦️ 27° · Cereté',first:'Yoleyda',users:[['YS','Yoleyda Sánchez','Propietaria','Acceso total'],['RS','Rafael Sánchez','Socio / esposo','Operación y finanzas'],['EP','Edwin Pérez','Encargado','Lotes e inventario'],['IA','Ing. Paola Díaz','Profesional técnico','Asistencia agronómica'],['MC','Marta C.','Consulta','Solo lectura']]}
};
const records={
 animals:[['Luna','LL-023','Brahman rojo','385 kg','14.2 L/día','Gestante','🐄'],['Esperanza','LL-041','Gyr lechero','342 kg','16.8 L/día','Lactancia','🐮'],['Manchita','LL-056','Cruce F1','198 kg','—','Levante','🐄'],['Lucero','LL-018','Brahman blanco','428 kg','12.5 L/día','Lactancia','🐮'],['Estrella','LL-062','Gyr','146 kg','—','Ternera','🐄'],['Centauro','LL-007','Brahman','612 kg','—','Reproductor','🐂']],
 ponds:[['Estanque Norte','PN-02','Cachama blanca','3.480 peces','620 g','78 días','🐟'],['Estanque Sur','PS-01','Cachama negra','2.910 peces','485 g','102 días','🐠'],['Alevinaje','PA-03','Cachama mixta','5.200 peces','92 g','24 días','🐟']],
 rice:[['Lote Norte','VY-L01','Fedearroz 67','18.5 ha','Macollamiento','62 días','🌾'],['Lote Canal','VY-L02','FL Fedearroz 68','12.2 ha','Floración','94 días','🌾'],['Lote Bajo','VY-L03','Fedearroz 2020','9.8 ha','Preparación','8 días','🚜'],['Lote Palma','VY-L04','Fedearroz 67','15.1 ha','Maduración','118 días','🌾']]
};
const inventory={libertad:[['Concentrado levante','12 bultos','20 bultos','Bajo'],['Vacuna aftosa','8 dosis','15 dosis','Bajo'],['Sal mineralizada','34 bultos','15 bultos','Disponible'],['Alimento peces 32%','48 bultos','20 bultos','Disponible'],['Desparasitante','22 dosis','10 dosis','Disponible']],villayolsa:[['Urea 46-0-0','18 bultos','25 bultos','Bajo'],['Herbicida selectivo','6 litros','10 litros','Bajo'],['Semilla Fedearroz 67','42 bultos','20 bultos','Disponible'],['Fertilizante DAP','31 bultos','15 bultos','Disponible'],['Fungicida preventivo','14 litros','8 litros','Disponible']]};
const roles=['Propietaria','Socio / esposo','Encargado','Profesional técnico','Consulta'];
let state={org:'libertad',view:'dashboard',role:0,user:0,weight:385,expense:18420000,activityAdded:false};
try{state={...state,...JSON.parse(localStorage.getItem('agronexo-demo')||'{}')}}catch{}
let chart;
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const money=n=>'$ '+Math.round(n).toLocaleString('es-CO');
function save(){localStorage.setItem('agronexo-demo',JSON.stringify(state))}
function farm(){return farms[state.org]}
function canEdit(){return state.role<4}
function enter(org){state.org=org;state.view='dashboard';state.role=0;state.user=0;save();$('#welcome').classList.add('hidden');$('#app').classList.remove('hidden');sync();render();}
$$('[data-enter]').forEach(b=>b.onclick=()=>enter(b.dataset.enter));
function sync(){const f=farm(),u=f.users[state.user]||f.users[0];$('#orgName').textContent=f.name;$('#orgOwner').textContent=f.owner;$('#orgEmoji').textContent=f.emoji;$('#crumbOrg').textContent=f.name;$('#weather').textContent=f.weather;$('#productionLabel').textContent=f.production;$('#secondaryLabel').textContent=f.secondary;$('#userName').textContent=u[1];$('#roleName').textContent=roles[state.role];$('#avatar').textContent=u[0];$('#pageTitle').textContent=`Buenos días, ${state.role===0?f.first:u[1].split(' ')[0]}`;$('#roleMenu').innerHTML=f.users.map((x,i)=>`<button data-user="${i}"><span>${x[0]}</span><span><b>${x[1]}</b><small>${x[2]}</small></span></button>`).join('');$$('[data-user]').forEach(b=>b.onclick=()=>{state.user=+b.dataset.user;state.role=+b.dataset.user;$('#roleMenu').classList.add('hidden');save();sync();render();toast(`Vista de ${roles[state.role]} activada`)});}
$('#orgButton').onclick=()=>$('#orgMenu').classList.toggle('hidden');$$('[data-org]').forEach(b=>b.onclick=()=>{state.org=b.dataset.org;state.view='dashboard';state.role=0;state.user=0;$('#orgMenu').classList.add('hidden');$('#chat').innerHTML='';$('#suggestions').innerHTML='';save();sync();render();});
$('#roleButton').onclick=()=>$('#roleMenu').classList.toggle('hidden');
$('#mobileMenu').onclick=()=>$('.sidebar').classList.toggle('open');
$('#notificationButton').onclick=()=>{state.view='alerts';render()};
$('#quickAdd').onclick=()=>openForm();
$('#agentFab').onclick=()=>openAgent();$('#closeAgent').onclick=()=>$('#agent').classList.add('hidden');
$$('#nav button[data-view]').forEach(b=>b.onclick=()=>{state.view=b.dataset.view;save();render();$('.sidebar').classList.remove('open')});
function title(t,sub){return `<div class="hero-row"><div><h3>${t}</h3><p>${sub}</p></div><div class="date-chip">Domingo, 2 de agosto de 2026</div></div>`}
function kpi(label,value,foot,icon,trend=''){return `<article class="kpi"><div class="kpi-top"><span>${label}</span><span class="kpi-icon">${icon}</span></div><div class="kpi-value">${value}</div><div class="kpi-foot ${trend.startsWith('+')?'up':trend.startsWith('-')?'down':''}">${trend?trend+' · ':''}${foot}</div></article>`}
function alerts(short=false){const a=state.org==='libertad'?[['danger','💉','Vacunación pendiente','Luna y 4 animales más','Vence mañana'],['','▦','Inventario bajo','Concentrado de levante','12 bultos'],['info','≈','Muestreo de biomasa','Estanque Norte','Hoy · 3:00 p.m.'],['','⚖','Control de peso','Lote de levante','Miércoles']]:[['danger','🌧','Lluvia intensa probable','38 mm entre 3–7 p.m.','Hoy'],['','◌','Fumigación programada','Lote Norte · Herbicida','Mañana'],['info','▦','Urea por debajo del mínimo','Disponible: 18 bultos','Comprar'],['','🌾','Cosecha próxima','Lote Palma','En 9 días']];return `<div class="alert-list">${a.slice(0,short?3:9).map(x=>`<div class="alert-item ${x[0]}"><span class="alert-dot">${x[1]}</span><span><b>${x[2]}</b><small>${x[3]}</small></span><time>${x[4]}</time></div>`).join('')}</div>`}
function dashboard(){const rice=state.org==='villayolsa';const ks=rice?[kpi('Área sembrada','45.8 ha','4 lotes activos','🌾','+8%'),kpi('Rendimiento esperado','6.4 t/ha','Meta: 6.1 t/ha','↗','+4.9%'),kpi('Costo del ciclo',money(state.expense+29600000),'72% del presupuesto','$','+2.1%'),kpi('Próxima cosecha','9 días','Lote Palma','◷')]:[kpi('Animales activos','126','94 hembras · 32 machos','🐄','+6'),kpi('Leche hoy','842 L','Promedio 8.9 L/vaca','🥛','+3.4%'),kpi('Biomasa estimada','4.12 t','3 estanques activos','🐟','+8.1%'),kpi('Saldo del mes',money(24680000-state.expense),'Ingresos $24,68 M','$','+12.5%')];return title(rice?'Resumen productivo de VillaYolsa':'Así marcha La Libertad',rice?'Seguimiento del ciclo arrocero y decisiones de hoy':'Indicadores clave de producción y gestión')+`<div class="kpi-grid">${ks.join('')}</div><div class="grid-2"><div class="panel"><div class="panel-head"><h4>${rice?'Costo acumulado por lote':'Producción de leche · últimos 7 días'}</h4><button class="link-button">VER REPORTE</button></div><div class="chart-wrap"><canvas id="mainChart"></canvas></div></div><div class="panel"><div class="panel-head"><h4>Prioridades de hoy</h4><button class="link-button" data-go="alerts">VER TODAS</button></div>${alerts(true)}</div></div><div class="panel" style="margin-top:14px"><div class="panel-head"><h4>Actividad reciente</h4><span class="status">Trazabilidad activa</span></div>${activityTable()}</div>`}
function activityTable(){const r=state.org==='libertad'?[['Registro de peso · Luna',`${state.weight} kg`,'José Martínez','Hoy, 8:42'],['Salida de concentrado','4 bultos','Carlos Suárez','Ayer, 16:18'],['Control pH · Estanque Norte','7.2 · Normal','José Martínez','Ayer, 10:05'],['Venta de leche','768 litros','Soledad Sánchez','1 ago, 17:30']]:[['Riego completado · Lote Canal','6 horas','Edwin Pérez','Hoy, 7:10'],['Aplicación de urea','8 bultos','Ing. Paola Díaz','Ayer, 15:45'],['Compra de herbicida','$ 780.000','Yoleyda Sánchez','Ayer, 9:20'],['Lectura humedad','72% · Lote Norte','Edwin Pérez','1 ago, 18:10']];if(state.activityAdded)r.unshift(['Actividad registrada por agente','Completada',farm().owner,'Ahora']);return `<table class="activity-table"><thead><tr><th>MOVIMIENTO</th><th>DETALLE</th><th>REGISTRADO POR</th><th>FECHA</th></tr></thead><tbody>${r.map(x=>`<tr>${x.map((v,i)=>`<td>${i===1?`<span class="status ${v==='Completada'?'':'pending'}">${v}</span>`:v}</td>`).join('')}</tr>`).join('')}</tbody></table>`}
function production(){const rice=state.org==='villayolsa',data=rice?records.rice:records.animals;return title(rice?'Lotes y ciclos de arroz':'Hato ganadero',rice?'Etapas, labores, costos y proyección por lote':'Expediente, sanidad, producción y genealogía de cada animal')+(!canEdit()?`<div class="permission-note">Modo consulta: puedes visualizar los registros, pero no modificarlos.</div>`:'')+`<div class="toolbar"><input class="search" placeholder="Buscar por nombre, código o estado…"><button class="filter">Todos los estados ⌄</button>${canEdit()?'<button class="primary" data-new>＋ Agregar</button>':''}</div><div class="cards-grid">${data.map((x,i)=>`<article class="record-card ${rice?'rice-card':''}" data-record="${i}"><div class="animal-photo"><span class="id">${x[1]}</span>${x[6]}</div><div class="record-body"><h4>${x[0]}</h4><p>${x[2]} · ${x[5]}</p><div class="record-stats"><span><b>${!rice&&i===0?state.weight+' kg':x[3]}</b><small>${rice?'ÁREA':'PESO'}</small></span><span><b>${x[4]}</b><small>${rice?'ETAPA':'PRODUCCIÓN'}</small></span><span><b>${x[5]}</b><small>${rice?'EDAD CULTIVO':'ESTADO'}</small></span></div></div></article>`).join('')}</div>`}
function secondary(){if(state.org==='villayolsa')return title('Ciclos productivos','Planificación integral desde la preparación hasta la cosecha')+`<div class="grid-2"><div class="panel"><h4>Línea de tiempo · Ciclo 2026-II</h4><div style="padding:24px 4px">${['Preparación','Siembra','Riego','Fertilización','Control fitosanitario','Cosecha'].map((x,i)=>`<div style="display:grid;grid-template-columns:22px 1fr 80px;gap:10px;margin:12px 0"><b style="color:${i<4?'var(--green)':'#aaa'}">${i<4?'●':'○'}</b><span style="font-size:11px">${x}</span><small>${i<4?'Completado':'Programado'}</small></div>`).join('')}</div></div><div class="panel"><h4>Recomendaciones agronómicas</h4>${alerts()}</div></div>`;return title('Piscicultura','Control de estanques, biomasa, alimentación y calidad de agua')+`<div class="cards-grid">${records.ponds.map((x,i)=>`<article class="record-card pond-card"><div class="animal-photo"><span class="id">${x[1]}</span>${x[6]}</div><div class="record-body"><h4>${x[0]}</h4><p>${x[2]} · Parámetros normales</p><div class="record-stats"><span><b>${x[3]}</b><small>POBLACIÓN</small></span><span><b>${x[4]}</b><small>PESO PROM.</small></span><span><b>${x[5]}</b><small>COSECHA EST.</small></span></div></div></article>`).join('')}</div>`}
function inventoryView(){const rows=inventory[state.org];return title('Inventario de insumos','Existencias, mínimos y movimientos por actividad')+`<div class="kpi-grid">${kpi('Referencias','38','5 categorías','▦')}${kpi('Valor estimado','$ 31,8 M','Actualizado hoy','$')}${kpi('Stock bajo','2','Requieren compra','!')}${kpi('Movimientos','17','Esta semana','↕')}</div><div class="panel" style="margin-top:14px"><table class="activity-table"><thead><tr><th>INSUMO</th><th>EXISTENCIA</th><th>MÍNIMO</th><th>ESTADO</th></tr></thead><tbody>${rows.map(x=>`<tr><td><b>${x[0]}</b></td><td>${x[1]}</td><td>${x[2]}</td><td><span class="status ${x[3]==='Bajo'?'danger':''}">${x[3]}</span></td></tr>`).join('')}</tbody></table></div>`}
function finance(){const rice=state.org==='villayolsa',income=rice?68500000:24680000;return title('Finanzas','Ingresos, gastos y rentabilidad con trazabilidad')+`<div class="kpi-grid">${kpi('Ingresos',money(income),'Mes actual','$','+12.5%')}${kpi('Gastos',money(state.expense),'Mes actual','↘','-3.1%')}${kpi('Saldo',money(income-state.expense),'Disponible','$')}${kpi(rice?'Costo / hectárea':'Margen operativo',rice?'$ 1,05 M':'25,4%','Dentro de meta','◎')}</div><div class="grid-2"><div class="panel"><div class="panel-head"><h4>Ingresos vs. gastos</h4><span class="status">Agosto 2026</span></div><div class="chart-wrap"><canvas id="financeChart"></canvas></div></div><div class="panel"><h4>Distribución de gastos</h4><div style="padding:20px 4px">${[['Insumos',42],['Mano de obra',28],['Mantenimiento',18],['Otros',12]].map(x=>`<div style="margin:13px 0;font-size:10px"><div style="display:flex;justify-content:space-between"><span>${x[0]}</span><b>${x[1]}%</b></div><div style="height:7px;background:#edf0eb;border-radius:8px;margin-top:6px"><i style="display:block;width:${x[1]}%;height:100%;background:var(--green);border-radius:8px"></i></div></div>`).join('')}</div></div></div>`}
function calendar(){return title('Agenda operativa','Actividades productivas, sanitarias y administrativas')+`<div class="panel"><div class="panel-head"><h4>Agosto 2026</h4><button class="primary">＋ Programar actividad</button></div><div class="calendar-grid">${Array.from({length:14},(_,i)=>`<div><b>${i+1}</b>${i===1?`<span class="event warn">${state.org==='libertad'?'Vacunar Luna':'Riego Lote Norte'}</span>`:''}${i===3?'<span class="event">Revisión inventario</span>':''}${i===7?`<span class="event">${state.org==='libertad'?'Muestreo estanque':'Fumigación L01'}</span>`:''}${i===10?'<span class="event warn">Pago proveedor</span>':''}</div>`).join('')}</div></div>`}
function team(){return title('Equipo y roles','Accesos separados por finca y permisos según responsabilidad')+`<div class="panel"><div class="panel-head"><h4>${farm().users.length} usuarios con acceso</h4>${state.role===0?'<button class="primary" id="inviteBtn">＋ Invitar usuario</button>':''}</div><div class="team-list">${farm().users.map((x,i)=>`<div class="team-member"><span class="member-avatar">${x[0]}</span><span><b>${x[1]}</b><small>${i===0?'Activo ahora':'Último acceso reciente'}</small></span><span class="status">${x[2]}</span><small>${x[3]}</small></div>`).join('')}</div></div><div class="permission-note" style="margin-top:14px">La Libertad y VillaYolsa son espacios independientes: ningún usuario ve datos de otra finca salvo invitación explícita.</div>`}
function render(){if($('#app').classList.contains('hidden'))return;const labels={dashboard:'Resumen',production:farm().production,secondary:farm().secondary,inventory:'Inventario',calendar:'Agenda',finance:'Finanzas',alerts:'Alertas',team:'Equipo y roles'};$('#crumbView').textContent=labels[state.view];$$('#nav button[data-view]').forEach(b=>b.classList.toggle('active',b.dataset.view===state.view));let html={dashboard:dashboard,production,secondary,inventory:inventoryView,calendar,finance,alerts:()=>title('Centro de alertas','Prioridades y recomendaciones para actuar a tiempo')+`<div class="grid-2"><div class="panel"><div class="panel-head"><h4>Alertas activas</h4><span class="status danger">3 prioritarias</span></div>${alerts()}</div><div class="panel"><h4>Canales de notificación</h4><div style="margin-top:15px">${[['Aplicación móvil','Activo'],['Correo electrónico','Activo'],['WhatsApp · Meta sandbox','Preparado para conexión final']].map(x=>`<div class="team-member" style="grid-template-columns:34px 1fr 120px;margin:8px 0"><span class="member-avatar">✓</span><span><b>${x[0]}</b><small>Configuración de demostración</small></span><span class="status">${x[1]}</span></div>`).join('')}</div></div></div>`,team}[state.view]();$('#content').innerHTML=html;$$('[data-go]').forEach(b=>b.onclick=()=>{state.view=b.dataset.go;render()});$$('[data-record]').forEach(b=>b.onclick=()=>detail(+b.dataset.record));$$('[data-new]').forEach(b=>b.onclick=()=>openForm());if($('#inviteBtn'))$('#inviteBtn').onclick=()=>invite();requestAnimationFrame(drawCharts)}
function drawCharts(){if(typeof Chart==='undefined')return;if(chart){chart.destroy();chart=null}const c=$('#mainChart')||$('#financeChart');if(!c)return;const rice=state.org==='villayolsa';const finance=c.id==='financeChart';chart=new Chart(c,{type:finance?'bar':'line',data:{labels:finance?['Mar','Abr','May','Jun','Jul','Ago']:(rice?['L. Norte','L. Canal','L. Bajo','L. Palma']:['Lun','Mar','Mié','Jue','Vie','Sáb','Dom']),datasets:finance?[{label:'Ingresos',data:[19,23,21,27,25,rice?68.5:24.7],backgroundColor:'#6fa47b',borderRadius:5},{label:'Gastos',data:[15,17,18,16,19,state.expense/1e6],backgroundColor:'#d8b865',borderRadius:5}]:[{label:rice?'Costo (millones)':'Litros',data:rice?[16,13,7,19]:[768,790,802,815,824,831,842],borderColor:'#237a4b',backgroundColor:'rgba(35,122,75,.12)',fill:true,tension:.4,pointRadius:3}]},options:{responsive:true,maintainAspectRatio:false,plugins:{legend:{display:finance}},scales:{x:{grid:{display:false}},y:{grid:{color:'#edf0eb'},ticks:{font:{size:9}}}}}})}
function detail(i){const rice=state.org==='villayolsa',x=(rice?records.rice:records.animals)[i];$('#modalContent').innerHTML=`<div class="detail-hero"><div class="big-emoji">${x[6]}</div><div><div class="eyebrow">${x[1]} · EXPEDIENTE DIGITAL</div><h3>${x[0]}</h3><p>${x[2]} · ${x[5]}</p></div></div>${rice?`<div class="kpi-grid" style="grid-template-columns:repeat(3,1fr)">${kpi('Área',x[3],'Registrada','▱')}${kpi('Etapa',x[4],'Ciclo activo','🌾')}${kpi('Edad',x[5],'Desde siembra','◷')}</div><h4>Próximas labores</h4>${alerts(true)}`:`<div class="kpi-grid" style="grid-template-columns:repeat(3,1fr)">${kpi('Peso',i===0?state.weight+' kg':x[3],'Último control','⚖')}${kpi('Producción',x[4],'Promedio diario','🥛')}${kpi('Sanidad','Al día','1 alerta próxima','💉')}</div><h4>Genealogía navegable</h4><div class="genealogy"><div class="family-card"><small>MADRE</small><br><b>Esperanza · LL-041</b></div><div class="family-card"><small>PADRE</small><br><b>Centauro · LL-007</b></div><div class="family-card"><small>CRÍA</small><br><b>Estrella · LL-062</b></div><div class="family-card"><small>ABUELA MATERNA</small><br><b>Lucero · LL-018</b></div></div>`}`;$('#modal').classList.remove('hidden')}
function openForm(type='registro'){if(!canEdit()){toast('Este rol tiene acceso de consulta únicamente');return}$('#modalContent').innerHTML=`<div class="eyebrow">NUEVO REGISTRO</div><h3>Registrar novedad</h3><p style="color:var(--muted);font-size:11px">Quedará asociado a ${farm().name} y al usuario ${farm().users[state.user][1]}.</p><form id="recordForm" class="form-grid"><label>Tipo<select><option>Actividad productiva</option><option>Compra / gasto</option><option>${state.org==='libertad'?'Peso de animal':'Labor de lote'}</option><option>Movimiento de inventario</option></select></label><label>Fecha<input type="date" value="2026-08-02"></label><label style="grid-column:1/-1">Descripción<input required value="${type==='peso'?'Peso de Luna: 392 kg':''}" placeholder="Describe la novedad"></label><label>Valor / cantidad<input placeholder="0"></label><label>Responsable<input value="${farm().users[state.user][1]}"></label><button class="primary" style="grid-column:1/-1">Guardar registro</button></form>`;$('#modal').classList.remove('hidden');$('#recordForm').onsubmit=e=>{e.preventDefault();state.activityAdded=true;save();closeModal();render();toast('Registro guardado y trazabilidad actualizada')};}
function invite(){if(state.role!==0)return;$('#modalContent').innerHTML=`<div class="eyebrow">ACCESOS</div><h3>Invitar a ${farm().name}</h3><form id="inviteForm" class="form-grid"><label>Nombre<input required placeholder="Nombre completo"></label><label>Correo<input required type="email" placeholder="persona@correo.com"></label><label>Rol<select>${roles.slice(1).map(r=>`<option>${r}</option>`).join('')}</select></label><label>Vigencia<select><option>Permanente</option><option>30 días</option></select></label><button class="primary" style="grid-column:1/-1">Enviar invitación simulada</button></form>`;$('#modal').classList.remove('hidden');$('#inviteForm').onsubmit=e=>{e.preventDefault();closeModal();toast('Invitación simulada enviada')};}
function closeModal(){$('#modal').classList.add('hidden')}$$('[data-close]').forEach(b=>b.onclick=closeModal);$('#modal').onclick=e=>{if(e.target===$('#modal'))closeModal()};
function toast(s){const t=$('#toast');t.textContent=s;t.classList.remove('hidden');setTimeout(()=>t.classList.add('hidden'),2400)}
function openAgent(){const p=$('#agent');p.classList.remove('hidden');if(!$('#chat').children.length){addMsg(`Hola, soy el agente de <strong>${farm().name}</strong>. Puedo consultar la operación y registrar novedades con datos demostrativos. ¿Qué necesitas?`,'bot');suggestions()}setTimeout(()=>$('#chatInput').focus(),100)}
function suggestions(){const s=state.org==='libertad'?['¿Qué animales debo vacunar?','Muéstrame a Luna','¿Cuánto concentrado queda?','Registra 392 kg para Luna']:['¿Qué hago hoy en Lote Norte?','¿Cuándo es la fumigación?','¿Cómo van los gastos?','Registra actividad completada'];$('#suggestions').innerHTML=s.map(x=>`<button>${x}</button>`).join('');$$('#suggestions button').forEach(b=>b.onclick=()=>ask(b.textContent))}
function addMsg(s,type){const d=document.createElement('div');d.className=`msg ${type}`;d.innerHTML=s;$('#chat').appendChild(d);$('#chat').scrollTop=$('#chat').scrollHeight}
function answer(q){const n=q.toLowerCase();if(state.org==='libertad'){if(n.includes('vacun'))return `Hay <strong>5 animales</strong> con vacunación próxima. La prioridad es <strong>Luna (LL-023)</strong>: refuerzo contra clostridiosis mañana.`;if(n.includes('luna')&&!n.includes('registra'))return `<strong>Luna · LL-023</strong><br>Brahman rojo · ${state.weight} kg · gestante. Madre: Esperanza. Padre: Centauro. <button class="link-button" onclick="window.showLuna()">Abrir expediente →</button>`;if(n.includes('concentrado'))return `Quedan <strong>12 bultos</strong> de concentrado de levante, por debajo del mínimo de 20. Sugiero comprar 10 bultos.`;if(n.includes('estanque'))return `El Estanque Norte tiene <strong>3.480 peces</strong>, peso promedio 620 g y parámetros de agua normales. Muestreo hoy a las 3:00 p.m.`;if(n.includes('392')||n.includes('registra')&&n.includes('peso')){if(!canEdit())return 'Tu rol es de consulta y no permite registrar pesos.';state.weight=392;state.activityAdded=true;save();render();return `Listo. Registré <strong>392 kg para Luna</strong>, +7 kg desde el último control. La hoja de vida y la gráfica quedaron actualizadas.`}}else{if(n.includes('lote norte')||n.includes('hago hoy'))return `Para <strong>Lote Norte</strong>: verificar lámina de agua a las 10:00, revisar maleza de borde y preparar la fumigación de mañana. Riesgo de lluvia después de las 3:00 p.m.`;if(n.includes('fumig'))return `La próxima fumigación es <strong>mañana a las 6:00 a.m.</strong> en Lote Norte. Hay herbicida para 60% del área; se recomienda completar inventario hoy.`;if(n.includes('gasto')||n.includes('finanz'))return `Gasto acumulado del ciclo: <strong>${money(state.expense+29600000)}</strong>. El costo por hectárea está 2,1% sobre el plan, principalmente por fertilización.`;if(n.includes('registra')||n.includes('completada')){if(!canEdit())return 'Tu rol es de consulta y no permite registrar actividades.';state.activityAdded=true;save();render();return `Hecho. Registré la <strong>actividad como completada</strong> a nombre de ${farm().users[state.user][1]}. Ya aparece en la trazabilidad.`}}if(n.includes('gasto'))return `Los gastos del mes son <strong>${money(state.expense)}</strong>. Puedes abrir Finanzas para ver el detalle.`;return `Puedo ayudarte con producción, inventarios, finanzas, alertas o registros. Prueba una de las preguntas sugeridas.`}
function ask(q){if(!q.trim())return;addMsg(q,'user');$('#chatInput').value='';setTimeout(()=>addMsg(answer(q),'bot'),320)}
$('#chatForm').onsubmit=e=>{e.preventDefault();ask($('#chatInput').value)};window.showLuna=()=>{detail(0)};
if(location.hash==='#demo'||localStorage.getItem('agronexo-entered')){enter(state.org)}
$$('[data-enter]').forEach(b=>b.addEventListener('click',()=>localStorage.setItem('agronexo-entered','1')));
