import {chromium} from 'playwright';
import assert from 'node:assert/strict';
import fs from 'node:fs';
fs.mkdirSync('evidence',{recursive:true});
const browser=await chromium.launch({headless:true});
const page=await browser.newPage({viewport:{width:1440,height:960}});
const errors=[]; page.on('console',m=>{if(m.type()==='error') errors.push(m.text())});page.on('pageerror',e=>errors.push(e.message));
const base=process.env.BASE_URL||'http://127.0.0.1:4173/';
await page.goto(base,{waitUntil:'networkidle'});
assert.ok(await page.getByText('Finca La Libertad',{exact:true}).first().isVisible());
await page.locator('[data-enter="libertad"]').click();
await page.waitForSelector('.kpi-grid');
assert.equal(await page.locator('#orgName').textContent(),'Finca La Libertad');
await page.screenshot({path:'evidence/la-libertad-desktop.png',fullPage:true});
await page.locator('[data-view="production"]').click();
assert.equal(await page.locator('[data-record]').count(),10);
await page.locator('[data-record="0"]').click();
assert.ok(await page.getByText('Genealogía navegable').isVisible());
assert.equal(await page.locator('.animal-album img').count(),3);
await page.locator('[data-animal="LL-041"]').click();
assert.ok(await page.locator('#modalContent h3').getByText('Esperanza',{exact:true}).isVisible());
await page.locator('#animalUpload').setInputFiles('assets/animals/cattle-01.jpg');
assert.ok(await page.getByText(/4 fotos en su álbum/).isVisible());
await page.screenshot({path:'evidence/animal-album-genealogy.png',fullPage:true});
await page.locator('[data-close]').click();
await page.locator('#agentFab').click();
await page.getByText('Registra 392 kg para Luna',{exact:true}).click();
await page.waitForTimeout(500);
assert.ok(await page.getByText(/Registré 392 kg para Luna/).isVisible());
await page.locator('#closeAgent').click();
await page.locator('[data-view="production"]').click();
assert.ok((await page.locator('[data-record="0"]').textContent()).includes('392 kg'));
await page.locator('[data-view="finance"]').click();
assert.equal(await page.locator('.finance-table tbody tr').count(),6);
await page.locator('#newExpense').click();
await page.locator('#expenseConcept').fill('Reparación de bebedero');
await page.locator('#expenseCategory').selectOption('Mantenimiento');
await page.locator('#expenseAmount').fill('125000');
await page.locator('#expenseSupport').fill('Factura DEMO-125');
await page.locator('#expenseForm button.primary').click();
assert.equal(await page.locator('.finance-table tbody tr').count(),7);
assert.ok(await page.getByText('Reparación de bebedero',{exact:true}).isVisible());
await page.screenshot({path:'evidence/finance-ledger.png',fullPage:true});
await page.locator('[data-view="alerts"]').click();
assert.ok(await page.getByText('Montería · AHORA',{exact:true}).isVisible());
assert.ok(await page.getByText('Lluvias intensas',{exact:true}).isVisible());
await page.screenshot({path:'evidence/climate-libertad.png',fullPage:true});
await page.locator('#orgButton').click();await page.locator('[data-org="villayolsa"]').click();
assert.equal(await page.locator('#orgName').textContent(),'VillaYolsa');
await page.locator('[data-view="production"]').click();assert.ok(await page.getByText('Lote Norte',{exact:true}).isVisible());
await page.locator('#agentFab').click();await page.getByText('¿Cuándo es la fumigación?',{exact:true}).click();await page.waitForTimeout(500);assert.ok(await page.getByText(/mañana a las 6:00 a.m./).isVisible());
await page.screenshot({path:'evidence/villayolsa-agent.png',fullPage:true});
await page.locator('#closeAgent').click();
await page.locator('[data-view="alerts"]').click();
assert.ok(await page.getByText('Cereté · AHORA',{exact:true}).isVisible());
assert.ok(await page.getByText('Ventana corta de fumigación',{exact:true}).isVisible());
await page.screenshot({path:'evidence/climate-villayolsa.png',fullPage:true});
await page.locator('[data-view="calendar"]').click();
await page.locator('#syncCalendar').click();
await page.locator('#calendarProvider').selectOption({label:'Microsoft Outlook / 365'});
await page.locator('#calendarEmail').fill('yoleyda@ejemplo.com');
await page.locator('#calendarForm button[type="submit"], #calendarForm button.primary').click();
assert.ok(await page.getByText('Microsoft Outlook / 365 conectado',{exact:true}).isVisible());
assert.ok(await page.getByText(/yoleyda@ejemplo.com/).isVisible());
assert.ok(await page.getByText('Toda la agenda de AgroNexo se replica automáticamente.',{exact:true}).isVisible());
assert.ok(await page.getByText('Reunión familiar ↙',{exact:true}).isVisible());
await page.screenshot({path:'evidence/calendar-sync.png',fullPage:true});
await page.setViewportSize({width:390,height:844});await page.reload({waitUntil:'networkidle'});await page.waitForTimeout(300);await page.screenshot({path:'evidence/mobile-dashboard.png',fullPage:true});
assert.equal(errors.length,0,'console errors: '+errors.join(' | '));
console.log(JSON.stringify({pass:true,flows:['10-animal fictional herd','navigable genealogy','per-animal photo album','multi-photo upload','agent weight action reflected in UI','traceable finance ledger and new expense','La Libertad climate center','VillaYolsa lots','agent fumigation query','VillaYolsa climate center','complete-agenda Outlook sync','mobile 390x844'],consoleErrors:errors.length,screenshots:8}));
await browser.close();
