import {chromium} from 'playwright';
import assert from 'node:assert/strict';
import fs from 'node:fs';
fs.mkdirSync('evidence',{recursive:true});
const browser=await chromium.launch({headless:true});
const page=await browser.newPage({viewport:{width:1440,height:960}});
const errors=[]; page.on('console',m=>{if(m.type()==='error') errors.push(m.text())});page.on('pageerror',e=>errors.push(e.message));
await page.goto('http://127.0.0.1:4173/',{waitUntil:'networkidle'});
assert.ok(await page.getByText('Finca La Libertad',{exact:true}).first().isVisible());
await page.locator('[data-enter="libertad"]').click();
await page.waitForSelector('.kpi-grid');
assert.equal(await page.locator('#orgName').textContent(),'Finca La Libertad');
await page.screenshot({path:'evidence/la-libertad-desktop.png',fullPage:true});
await page.locator('[data-view="production"]').click();
await page.locator('[data-record="0"]').click();
assert.ok(await page.getByText('Genealogía navegable').isVisible());
await page.locator('[data-close]').click();
await page.locator('#agentFab').click();
await page.getByText('Registra 392 kg para Luna',{exact:true}).click();
await page.waitForTimeout(500);
assert.ok(await page.getByText(/Registré 392 kg para Luna/).isVisible());
await page.locator('#closeAgent').click();
await page.locator('[data-view="production"]').click();
assert.ok((await page.locator('[data-record="0"]').textContent()).includes('392 kg'));
await page.locator('#orgButton').click();await page.locator('[data-org="villayolsa"]').click();
assert.equal(await page.locator('#orgName').textContent(),'VillaYolsa');
await page.locator('[data-view="production"]').click();assert.ok(await page.getByText('Lote Norte',{exact:true}).isVisible());
await page.locator('#agentFab').click();await page.getByText('¿Cuándo es la fumigación?',{exact:true}).click();await page.waitForTimeout(500);assert.ok(await page.getByText(/mañana a las 6:00 a.m./).isVisible());
await page.screenshot({path:'evidence/villayolsa-agent.png',fullPage:true});
await page.setViewportSize({width:390,height:844});await page.reload({waitUntil:'networkidle'});await page.waitForTimeout(300);await page.screenshot({path:'evidence/mobile-dashboard.png',fullPage:true});
assert.equal(errors.length,0,'console errors: '+errors.join(' | '));
console.log(JSON.stringify({pass:true,flows:['La Libertad dashboard','animal genealogy','agent weight action reflected in UI','VillaYolsa lots','agent fumigation query','mobile 390x844'],consoleErrors:errors.length,screenshots:3}));
await browser.close();
