import assert from 'node:assert/strict';
import fs from 'node:fs';
const html=fs.readFileSync(new URL('./index.html',import.meta.url),'utf8');
const js=fs.readFileSync(new URL('./app.js',import.meta.url),'utf8');
for(const text of ['Finca La Libertad','Soledad Sánchez','VillaYolsa','Yoleyda Sánchez','ALMA']) assert.ok((html+js).includes(text),`missing ${text}`);
assert.ok((html+js).toLowerCase().includes('datos de demostración'),'missing demo-data label');
for(const view of ['dashboard','production','secondary','inventory','calendar','finance','alerts','team']) assert.ok(html.includes(`data-view="${view}"`),`missing view ${view}`);
assert.ok(js.includes('registrar')&&js.includes('localStorage'),'agent actions and session persistence');
assert.ok(js.includes('animalMedia')&&js.includes('uploadedMedia')&&js.includes('data-animal'),'animal albums, uploads and navigable genealogy');
assert.ok(js.includes("['Milagrosa','LL-079'")&&js.includes("['Titán','LL-075'"),'expanded fictional herd');
assert.ok(js.includes('calendarConnections')&&js.includes('Google Calendar')&&js.includes('Microsoft Outlook / 365')&&js.includes('CalDAV'),'per-user external calendar flow');
assert.ok(js.includes('financeEntries')&&js.includes('expense-ledger')&&js.includes('openExpense'),'traceable finance ledger');
assert.ok(js.includes('climateData')&&js.includes('alertsView')&&js.includes("place:'Montería'")&&js.includes("place:'Cereté'"),'climate centers for both farms');
assert.ok(js.includes('Toda la agenda de AgroNexo se replica automáticamente'),'complete agenda synchronization scope');
assert.ok(html.includes('sidebarBackdrop')&&js.includes('closeTransientMenus')&&js.includes("document.addEventListener('pointerdown'"),'click-away closure for drawers and dropdown menus');
console.log('PASS: contenido, módulos, dos fincas, agente y persistencia presentes');
